server:
  port: 8081
  address: ${SERVER_URL:0.0.0.0}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:xxx@gmail.com}
    password: ${MAIL_PASSWORD:xxx}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.protocols: TLSv1.2
springdoc:
  swagger-ui:
    csrf:
      enabled: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:secret_key}
      expiration: ${JWT_EXPIRATION:86400000}
logging:
  level:
    root: info

aws:
  endpointUrl: ${ENDPOINT:https://video-storage-v1.s3.ap-south-1.amazonaws.com}
  accessKey: ${ACCESS_KEY:AKIA4MTWGUI7UYFLIF5K}
  secretKey: ${SECRET_KEY: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}
  bucketName: ${BUCKET_NAME:video-storage-v1}
  region: ${REGION:ap-south-1}
app:
  client:
    url: ${CLIENT_URL:http://localhost:5173}